package media

import (
	"strings"
	"testing"
)

// Real leading bytes, captured from files generated by ffmpeg.
var sniffSamples = map[string][]byte{
	"image/jpeg": {0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 'J', 'F', 'I', 'F'},
	"image/png":  {0x89, 'P', 'N', 'G', 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 0x0d, 'I', 'H', 'D', 'R'},
	"image/gif":  []byte("GIF89a\x40\x00\x40\x00"),
	"image/webp": append([]byte("RIFF\x38\x0a\x00\x00WEBPVP8X"), make([]byte, 8)...),
	"image/avif": {0, 0, 0, 0x20, 'f', 't', 'y', 'p', 'a', 'v', 'i', 'f', 0, 0, 0, 0, 'a', 'v', 'i', 'f'},
	"video/mp4":  {0, 0, 0, 0x20, 'f', 't', 'y', 'p', 'i', 's', 'o', 'm', 0, 0, 2, 0, 'i', 's', 'o', 'm'},
	"video/webm": append([]byte{0x1a, 0x45, 0xdf, 0xa3, 0x9f, 0x42, 0x86, 0x81, 0x01, 0x42, 0xf7, 0x81,
		0x01, 0x42, 0xf2, 0x81, 0x04, 0x42, 0xf3, 0x81, 0x08, 0x42, 0x82, 0x84}, []byte("webm")...),
}

func TestSniffRecognisesEveryAllowedType(t *testing.T) {
	for want, header := range sniffSamples {
		if got := Sniff(header); got != want {
			t.Errorf("Sniff(%s sample) = %q, want %q", want, got, want)
		}
	}
}

func TestEverySniffableTypeIsAllowed(t *testing.T) {
	for mime := range sniffSamples {
		if !IsAllowedMime(mime) {
			t.Errorf("Sniff can produce %q but IsAllowedMime rejects it", mime)
		}
	}
	if len(AllowedMimes) != len(sniffSamples) {
		t.Errorf("AllowedMimes has %d entries but there are %d sniffable types", len(AllowedMimes), len(sniffSamples))
	}
}

func TestSniffRejectsDangerousAndUnknownTypes(t *testing.T) {
	dangerous := map[string][]byte{
		// An SVG served same-origin from /m/ executes script and steals the
		// session cookie. This is the single most important rejection here.
		"svg with xml prolog": []byte(`<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>`),
		"bare svg":            []byte(`<svg xmlns="http://www.w3.org/2000/svg" onload="alert(1)"/>`),
		"html":                []byte("<!DOCTYPE html><html><body><script>alert(1)</script></body></html>"),
		"html no doctype":     []byte("<html><head><title>x</title></head></html>"),
		"plain text":          []byte("just some text, nothing to see here at all"),
		"empty":               {},
		"short":               {0x89, 'P'},
		"pdf":                 []byte("%PDF-1.7\n%\xe2\xe3\xcf\xd3\n1 0 obj"),
		"zip":                 {'P', 'K', 0x03, 0x04, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		"elf binary":          {0x7f, 'E', 'L', 'F', 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		"shell script":        []byte("#!/bin/sh\nrm -rf /\n"),
		// Matroska shares the EBML magic with WebM but is not on the allowlist.
		"matroska": append([]byte{0x1a, 0x45, 0xdf, 0xa3, 0x9f, 0x42, 0x86, 0x81, 0x01,
			0x42, 0x82, 0x88}, []byte("matroska")...),
		// RIFF but not WEBP.
		"riff wav": []byte("RIFF\x24\x08\x00\x00WAVEfmt "),
		// ftyp but an unlisted brand.
		"quicktime": {0, 0, 0, 0x14, 'f', 't', 'y', 'p', 'q', 't', ' ', ' ', 0, 0, 0, 0},
	}
	for name, header := range dangerous {
		if got := Sniff(header); got != "" {
			t.Errorf("Sniff(%s) = %q, want \"\" (unrecognised)", name, got)
		}
	}
}

func TestIsAllowedMimeRejectsActiveContent(t *testing.T) {
	for _, mime := range []string{
		"image/svg+xml", "text/html", "application/xhtml+xml", "text/plain",
		"application/javascript", "application/pdf", "video/x-matroska", "",
	} {
		if IsAllowedMime(mime) {
			t.Errorf("IsAllowedMime(%q) = true; that type must never be served same-origin", mime)
		}
	}
}

func TestSniffLenIsEnoughForEverySignature(t *testing.T) {
	if SniffLen < 64 {
		t.Fatalf("SniffLen = %d, too small for the WebM DocType scan", SniffLen)
	}
	for want, header := range sniffSamples {
		if len(header) > SniffLen {
			t.Errorf("the %s sample needs %d bytes but SniffLen is %d", want, len(header), SniffLen)
		}
	}
}

func TestExtForMime(t *testing.T) {
	want := map[string]string{
		"image/jpeg": "jpg", "image/png": "png", "image/gif": "gif",
		"image/webp": "webp", "image/avif": "avif",
		"video/mp4": "mp4", "video/webm": "webm",
	}
	for mime, ext := range want {
		got := ExtForMime(mime)
		if got != ext {
			t.Errorf("ExtForMime(%q) = %q, want %q", mime, got, ext)
		}
		if strings.HasPrefix(got, ".") {
			t.Errorf("ExtForMime(%q) = %q, want no leading dot", mime, got)
		}
	}
	if got := ExtForMime("image/svg+xml"); got != "" {
		t.Errorf("ExtForMime of a disallowed type = %q, want \"\"", got)
	}
}

func TestIsVideoMime(t *testing.T) {
	for _, m := range []string{"video/mp4", "video/webm"} {
		if !IsVideoMime(m) {
			t.Errorf("IsVideoMime(%q) = false, want true", m)
		}
	}
	for _, m := range []string{"image/png", "image/gif", "image/webp", ""} {
		if IsVideoMime(m) {
			t.Errorf("IsVideoMime(%q) = true, want false", m)
		}
	}
}

func TestIsGifMime(t *testing.T) {
	if !IsGifMime("image/gif") {
		t.Error("IsGifMime(image/gif) = false, want true")
	}
	// A GIF is not a video by IsVideoMime's split, but it must still report
	// true here: the two are independent checks, not one replacing the
	// other, since GenerateThumbnail keys off IsVideoMime for the seek
	// decision while the web layer keys off IsGifMime for preview wiring.
	if IsVideoMime("image/gif") {
		t.Error("IsVideoMime(image/gif) = true, want false: GIF needs the still-image seek behaviour")
	}
	for _, m := range []string{"image/png", "image/webp", "video/mp4", "video/webm", ""} {
		if IsGifMime(m) {
			t.Errorf("IsGifMime(%q) = true, want false", m)
		}
	}
}
